### ISSUE TITLE
cross-compile broken for commits after e45ae429b9ca8f234eb861338a75b2d89cde206a

### ISSUE THREAD

**Issue by hydra3333** [mstorsjo/fdk-aac#94]
Hello.  Commit e45ae429b9ca8f234eb861338a75b2d89cde206a works, but with anything after that, 
cross-compiling under minw64/ubuntu latest is totally borked, throwing errors like this:
```
[16:45:47][DEBUG] Running 'make  -j 2' in '/home/u/Desktop/workdir/x86_64/fdk-aac_git'
  CXX      libAACdec/src/aac_ram.lo
  CXX      libAACdec/src/FDK_delay.lo
In file included from libAACdec/src/aac_rom.h:106,
                 from libAACdec/src/FDK_delay.h:106,
                 from libAACdec/src/FDK_delay.cpp:103:
./libFDK/include/common_fix.h:410:18: error: redefinition of 'SHORT fMax(SHORT, SHORT)'
 FDK_INLINE SHORT fMax(SHORT a, SHORT b) { return fixmax_S(a, b); }
                  ^~~~
./libFDK/include/common_fix.h:404:21: note: 'FIXP_SGL fMax(FIXP_SGL, FIXP_SGL)' previously defined here
 FDK_INLINE FIXP_SGL fMax(FIXP_SGL a, FIXP_SGL b) { return fixmax_S(a, b); }
                     ^~~~
./libFDK/include/common_fix.h:411:18: error: redefinition of 'SHORT fMin(SHORT, SHORT)'
 FDK_INLINE SHORT fMin(SHORT a, SHORT b) { return fixmin_S(a, b); }
                  ^~~~
./libFDK/include/common_fix.h:403:21: note: 'FIXP_SGL fMin(FIXP_SGL, FIXP_SGL)' previously defined here
 FDK_INLINE FIXP_SGL fMin(FIXP_SGL a, FIXP_SGL b) { return fixmin_S(a, b); }
                     ^~~~
In file included from libAACdec/src/aac_ram.h:106,
                 from libAACdec/src/aac_ram.cpp:103:
./libFDK/include/common_fix.h:410:18: error: redefinition of 'SHORT fMax(SHORT, SHORT)'
 FDK_INLINE SHORT fMax(SHORT a, SHORT b) { return fixmax_S(a, b); }
                  ^~~~
./libFDK/include/common_fix.h:404:21: note: 'FIXP_SGL fMax(FIXP_SGL, FIXP_SGL)' previously defined here
 FDK_INLINE FIXP_SGL fMax(FIXP_SGL a, FIXP_SGL b) { return fixmax_S(a, b); }
                     ^~~~
./libFDK/include/common_fix.h:411:18: error: redefinition of 'SHORT fMin(SHORT, SHORT)'
 FDK_INLINE SHORT fMin(SHORT a, SHORT b) { return fixmin_S(a, b); }
                  ^~~~
./libFDK/include/common_fix.h:403:21: note: 'FIXP_SGL fMin(FIXP_SGL, FIXP_SGL)' previously defined here
 FDK_INLINE FIXP_SGL fMin(FIXP_SGL a, FIXP_SGL b) { return fixmin_S(a, b); }
                     ^~~~
Makefile:1575: recipe for target 'libAACdec/src/FDK_delay.lo' failed
make: *** [libAACdec/src/FDK_delay.lo] Error 1
make: *** Waiting for unfinished jobs....
Makefile:1575: recipe for target 'libAACdec/src/aac_ram.lo' failed
make: *** [libAACdec/src/aac_ram.lo] Error 1
```
using
`./configure --host=x86_64-w64-mingw32 --prefix=/home/u/Desktop/workdir/toolchain/x86_64-w64-mingw32/x86_64-w64-mingw32 --disable-shared --enable-static in /home/u/Desktop/workdir/x86_64/fdk-aac_git`

**Comment by mstorsjo** [comment]
Thanks, this should be fixed now.

**Comment by hydra3333** [comment]
Thanks !
